Add a bash handlers example.

diff --git a/85_tini/bash/Dockerfile.handlers b/85_tini/bash/Dockerfile.handlers
--- a/85_tini/bash/Dockerfile.handlers
+++ b/85_tini/bash/Dockerfile.handlers
@@ -9,6 +9,48 @@ RUN apt-get update \
 
 COPY --chmod=755 <<EOF /bin/ping.sh
 #!/usr/bin/env bash
+set -euf -o pipefail
+echo "Waiting..."
+
+function trap_hup_handler() {
+    echo "SIGHUP handler exiting"
+    exit $(( 128 + 1 ))
+}
+function trap_int_handler() {
+    echo "SIGINT handler exiting"
+    exit $(( 128 + 2 ))
+}
+function trap_quit_handler() {
+    echo "SIGQUIT handler exiting"
+    exit $(( 128 + 3 ))
+}
+function trap_term_handler() {
+    echo "SIGTERM handler exiting"
+    exit $(( 128 + 15 ))
+}
+function ctrlc_script() {
+    echo "CTRL+C exiting"
+    exit
+}
+function error_exit() {
+    echo "TRAPPED: Error exitcode"
+    # you can overwrite the exit code.
+    #exit 0
+}
+function exit_script() {
+    echo "TRAPPED: exit_script"
+    # you can overwrite the exit code.
+    #exit 0
+}
+
+trap exit_script EXIT
+trap error_exit ERR
+trap ctrlc_script INT
+trap trap_hup_handler SIGHUP
+trap trap_int_handler SIGINT
+trap trap_quit_handler SIGQUIT
+trap trap_term_handler SIGTERM
+
 while true; do 
     curl -L --connect-timeout 5 --max-time 20 --retry 5 --retry-delay 0 --retry-max-time 40 -v http://www.google.com
     sleep 3;
